server:
    port: 8081
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${ENTRA_ISSUER_URI:https://login.microsoftonline.com/8a91e271-d2b1-4665-9ca3-cf16ab3493bb/v2.0}
                    audiences:
                        - ${ENTRA_API_CLIENT_ID:c1918f98-96be-4384-b994-b7e7e7553df0}

microservices:
    usuarios:
        base-url: ${MS_USUARIOS_URL:http://localhost:8083}
    productos:
        base-url: ${MS_PRODUCTOS_URL:http://localhost:8084}
    pedidos:
        base-url: ${MS_PEDIDOS_URL:http://localhost:8085}